### ISSUE TITLE
ImportError: cannot import name 'PropensityEvaluator' from 'causallib.estimation'

### ISSUE THREAD

**Issue by GiacomoPinardi** [IBM/causallib#23]
On Google Colab, after installing `causallib` from PiP I try to import the `PropensityEvaluator`, but it fails.

    !pip install causallib
    from causallib.estimation import IPW, PropensityEvaluator

Collecting causallib
  Downloading causallib-0.7.1-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 5.1 MB/s 
Requirement already satisfied: numpy<2,>=1.13 in /usr/local/lib/python3.7/dist-packages (from causallib) (1.19.5)
Requirement already satisfied: matplotlib<4,>=2.2 in /usr/local/lib/python3.7/dist-packages (from causallib) (3.2.2)
Requirement already satisfied: scipy<2,>=0.19 in /usr/local/lib/python3.7/dist-packages (from causallib) (1.4.1)
Requirement already satisfied: networkx<3,>=1.1 in /usr/local/lib/python3.7/dist-packages (from causallib) (2.6.3)
Requirement already satisfied: statsmodels<1,>=0.8 in /usr/local/lib/python3.7/dist-packages (from causallib) (0.10.2)
Requirement already satisfied: pandas<2,>=0.25.2 in /usr/local/lib/python3.7/dist-packages (from causallib) (1.1.5)
Requirement already satisfied: scikit-learn<2,>=0.20 in /usr/local/lib/python3.7/dist-packages (from causallib) (1.0.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib<4,>=2.2->causallib) (3.0.6)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib<4,>=2.2->causallib) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib<4,>=2.2->causallib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib<4,>=2.2->causallib) (0.11.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas<2,>=0.25.2->causallib) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib<4,>=2.2->causallib) (1.15.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn<2,>=0.20->causallib) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn<2,>=0.20->causallib) (3.0.0)
Requirement already satisfied: patsy>=0.4.0 in /usr/local/lib/python3.7/dist-packages (from statsmodels<1,>=0.8->causallib) (0.5.2)
Installing collected packages: causallib
Successfully installed causallib-0.7.1

**ImportError: cannot import name 'PropensityEvaluator' from 'causallib.estimation' (/usr/local/lib/python3.7/dist-packages/causallib/estimation/__init__.py)**

I can't understand why this happens. In my local machine, I can run this snippet without problems.

Google Colab uses Python 3.7.12

**Comment by ehudkr** [comment]
Hi Giacomo, `Evaluator` objects are found under the `causallib.evaluation` module, not the `estimation` module 🙂 . 
The snippet below works for me on colab:
```python
!pip install causallib
from causallib.estimation import IPW
from causallib.evaluation import PropensityEvaluator
```

However, I'm intrigued how importing `PropensityEvaluator` from `causallib.estimation` worked for you locally, could you please double check?

**Comment by GiacomoPinardi** [comment]
Sorry, I've double-checked and I refactored the code without running it. 
So, as expected, locally it doesn't work too.

Thank you for your help and this great package!
